version: '3'
services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - envs/development.env
    networks:
      - boilerplate_flask
    ports:
      - ${SERVER_HOST_PORT}:5000
      - ${SERVER_DEBUG_HOST_PORT}:5678
    volumes:
      - ./:/workspace/hskwon/boilerplate_flask
networks:
  boilerplate_flask:
