version: '3'
services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - envs/development.env
    networks:
      - boilerplate_flask
    ports:
      - ${SERVER_HOST_PORT}:5000
      - ${SERVER_DEBUG_HOST_PORT}:5678
    restart: unless-stopped
    volumes:
      - ./:/workspace/hskwon/boilerplate_flask
  database:
    build: 
      context: ./Dockerfiles/database/
      dockerfile: Dockerfile
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./Dockerfiles/database/envs/development.env
    networks:
      - boilerplate_flask
    ports:
      - '${DATABASE_HOST_PORT}:3306'
    restart: unless-stopped
networks:
  boilerplate_flask:
